export const SET_CLIENTS = 'SET_CLIENTS';
export const SET_CLIENT = 'SET_CLIENT';
export const ADD_CLIENT = 'ADD_CLIENT';
export const UPDATE_CLIENT = 'UPDATE_CLIENT';
export const SET_CLIENT_ORGANIZATIONS = 'SET_CLIENT_ORGANIZATIONS';
export const ADD_CLIENT_ORGANIZATION = 'ADD_CLIENT_ORGANIZATION';

export default {
  SET_CLIENTS,
  SET_CLIENT,
  ADD_CLIENT,
  UPDATE_CLIENT,
  SET_CLIENT_ORGANIZATIONS,
  ADD_CLIENT_ORGANIZATION,
};
