require: rubocop-rspec

AllCops:
  # Include gemspec and Rakefile
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'spec/**/*'
  Exclude:
    - 'vendor/**/*'
    - 'db/*rb'
    - 'db/migrate/*rb'
    - 'bin/**/*'
    - 'spec/support/**/*.json'
  DisplayCopNames: true
  StyleGuideCopsOnly: false

Style/Documentation:
  Enabled: false
  Exclude:
    - 'lib/**/version.rb'

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Style/BarePercentLiterals:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

RSpec/NestedGroups:
  Max: 4
