export const SET_ORGANIZATIONS = 'SET_ORGANIZATIONS';
export const ADD_ORGANIZATION = 'ADD_ORGANIZATION';
export const DESTROY_ORGANIZATION = 'DESTROY_ORGANIZATION';
DESTROY_ORGANIZATION

export default {
  SET_ORGANIZATIONS,
  ADD_ORGANIZATION,
  DESTROY_ORGANIZATION,
};
