export const SET_ORGANIZATIONS = 'SET_ORGANIZATIONS';
export const SET_ORGANIZATION = 'SET_ORGANIZATION';
export const ADD_ORGANIZATION = 'ADD_ORGANIZATION';
export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION';
export const DESTROY_ORGANIZATION = 'DESTROY_ORGANIZATION';
export const SET_ORGANIZATION_CLIENTS = 'SET_ORGANIZATION_CLIENTS';
export const ADD_ORGANIZATION_CLIENT = 'ADD_ORGANIZATION_CLIENT';

export default {
  SET_ORGANIZATIONS,
  SET_ORGANIZATION,
  ADD_ORGANIZATION,
  UPDATE_ORGANIZATION,
  DESTROY_ORGANIZATION,
  SET_ORGANIZATION_CLIENTS,
  ADD_ORGANIZATION_CLIENT,
};
