default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

dev_defult: &dev_default
  <<: *default
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>

development:
  <<: *dev_default
  database: <%= ENV['DATABASE_NAME_DEV'] %>

test:
  <<: *dev_default
  database: <%= ENV['DATABASE_NAME_TEST'] %>

production:
  <<: *default
  username: <%= Rails.application.credentials.dig(:database_username) %>
  password: <%= Rails.application.credentials.dig(:database_password) %>
  database: <%= Rails.application.credentials.dig(:database_name) %>
