export const SET_EQUIPMENTS = 'SET_EQUIPMENTS';
export const SET_EQUIPMENT = 'SET_EQUIPMENT';
export const SET_EQUIPMENT_TYPES = 'SET_EQUIPMENT_TYPES';
export const ADD_EQUIPMENT = 'ADD_EQUIPMENT';
export const UPDATE_EQUIPMENT = 'UPDATE_EQUIPMENT';

export default {
  SET_EQUIPMENTS,
  SET_EQUIPMENT,
  ADD_EQUIPMENT,
  UPDATE_EQUIPMENT,
  SET_EQUIPMENT_TYPES,
};
